# Generated by Django 4.1.5 on 2023-02-02 12:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('aw', 'ожидает'), ('act', 'активный'), ('comp', 'завершён')], default='aw', max_length=4, verbose_name='Статус')),
            ],
        ),
    ]
